// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwXlg_RuDxrbOEYk8LxNr_IxfbqLLWLKw',
    appId: '1:295854574986:web:823f2f74736941bcd94c73',
    messagingSenderId: '295854574986',
    projectId: 'flutter-training-892b0',
    authDomain: 'flutter-training-892b0.firebaseapp.com',
    storageBucket: 'flutter-training-892b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZ2RANWcKjvgYV0W_BXSLw424yjbjmFA',
    appId: '1:295854574986:android:64795cb4412292ded94c73',
    messagingSenderId: '295854574986',
    projectId: 'flutter-training-892b0',
    storageBucket: 'flutter-training-892b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY27uQcjgWXSIXzJ6gEUVxvQkwsgfSmwE',
    appId: '1:295854574986:ios:231021904aab3892d94c73',
    messagingSenderId: '295854574986',
    projectId: 'flutter-training-892b0',
    storageBucket: 'flutter-training-892b0.appspot.com',
    iosClientId: '295854574986-ol9gna5bspmcjblekll016kbucp4335c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY27uQcjgWXSIXzJ6gEUVxvQkwsgfSmwE',
    appId: '1:295854574986:ios:231021904aab3892d94c73',
    messagingSenderId: '295854574986',
    projectId: 'flutter-training-892b0',
    storageBucket: 'flutter-training-892b0.appspot.com',
    iosClientId: '295854574986-ol9gna5bspmcjblekll016kbucp4335c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
